/* -------------------------------------------------------
test
Generated by blokdots (0.5.4) · 10/23/2022, 5:37:14 PM
------------------------------------------------------- */

var blokdots = require("@blokdots/components");
var five = require("johnny-five");

// ------------- Setup the board -------------
var board = new five.Board();

// --- Setup vars ---
var button;
var led;
var slidePotentiometer;
var buzzer;
var protoPiePlayer;
var ledStrip;

// ------------- IFTTT -------------

// Turn Light On Test
function turnLightOnTestReaction() {
  led.on()
}

function turnStrobeLightsOn(){
  ledStrip.on();
}

// Card 2
function card2Reaction(value) {
  protoPiePlayer.send({
    message: "Emotion Changing",
    value: value
  })
}

// Card 3
function card3Reaction(value) {
  protoPiePlayer.send({
    message: "Raised hand",
    value: value
  })
}

// Card 4
function card4Reaction(value) {
  protoPiePlayer.send({
    message: "Asked for help",
    value: value
  })
}

// Card 5
function card5Reaction() {
  buzzer.frequency(587, 1000);
}

// ------------- Run -------------
board.on('ready', function() {
  // --- Setup components ---
  button = new five.Button({
    pin: 2,
    holdtime: 1000
  });
  ledStrip = new five.Led.RGB({pin: 6});
  led = new five.Led(4);
  slidePotentiometer = new five.Sensor("A0");
  buzzer = new five.Piezo(5);
  protoPiePlayer = new blokdots.SocketIOIntegration("protopie", "ppMessage", {
    "message": "messageId",
    "value": "value"
  });

  // --- Setup event listeners ---

  // Turn Light On Test
  protoPiePlayer.on("received", function(message) {
    if (message.message === "Prompt Sent") {
      turnLightOnTestReaction(message.value);
    }
  });

  // Card 2
  slidePotentiometer.on("change", function(value) {
    card2Reaction(value);
  });

  // Card 3
  var card3Counter = 0;
  button.on("down", function() {
    card3Counter++;
    if (card3Counter >= 1) {
      card3Counter = 0;
      card3Reaction();
    }
  });

  // Card 4
  var card4Counter = 0;
  button.on("down", function() {
    card4Counter++;
    if (card4Counter >= 2) {
      card4Counter = 0;
      card4Reaction();
    }
  });

  // Card 5
  var card5Counter = 0;
  button.on("down", function() {
    card5Counter++;
    if (card5Counter >= 2) {
      card5Counter = 0;
      card5Reaction();
    }
  });
});

// ------------- Stop -------------
function stop() {
  // --- Remove event listeners ---
  if (button && button._events) {
    button.removeAllListeners();
  }
  if (led && led._events) {
    led.removeAllListeners();
  }
  if (slidePotentiometer && slidePotentiometer._events) {
    slidePotentiometer.removeAllListeners();
  }
  if (buzzer && buzzer._events) {
    buzzer.removeAllListeners();
  }
  if (protoPiePlayer && protoPiePlayer._events) {
    protoPiePlayer.removeAllListeners();
  }
}